app = "abc-metrics-metabase"
primary_region = "iad"

[build]
  image = "metabase/metabase:latest"

[env]
  MB_JETTY_PORT = "3000"
  MB_JETTY_HOST = "0.0.0.0"
  MB_DB_TYPE = "postgres"
  MB_DB_DBNAME = "fly-db"
  MB_DB_PORT = "5432"
  MB_DB_USER = "fly-user"
  MB_DB_PASS = "mJHdkZbWGckg31sOb5RASQo3"
  MB_DB_HOST = "pgbouncer.9g6y30w2qg60v5ml.flympg.net"
  JAVA_TIMEZONE = "UTC"
  JAVA_OPTS = "-Xmx1024m -Xms512m"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048
  processes = ["app"]

